### ISSUE TITLE
AdamW bug

### ISSUE THREAD

**Issue by wyanb** [zhiyuanyou/UniAD#5]
[2022-10-10 10:01:45,308][cifar_dataset.py][line:  35][    INFO] building CustomDataset from: ../../../data/CIFAR-10/
/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:370: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  "please use `get_last_lr()`.", UserWarning)
/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  "The default behavior for interpolate/upsample with float scale_factor changed "
Traceback (most recent call last):
  File "../../../tools/train_val.py", line 329, in <module>
    main()
  File "../../../tools/train_val.py", line 143, in main
    frozen_layers,
  File "../../../tools/train_val.py", line 221, in train_one_epoch
    optimizer.step()
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/optim/adamw.py", line 117, in step
    beta1,
UnboundLocalError: local variable 'beta1' referenced before assignment
Killing subprocess 3774
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)

**Comment by zhiyuanyou** [comment]
Well, I guess you used pytorch 1.8.
This is a bug of pytorch 1.8 (not ours). You have 3 options to revise: 
(1) change pytorch from 1.8 to 1.5.
OR
(2) run about 5 times and there maybe 1 time you could pass this bug.
OR
(3) revise a line in the source code of pytorch (I will find a instruction today and paste it below).

**Comment by wyanb** [comment]
I tried a few more times and it avoided the bug, thank you

**Comment by zhiyuanyou** [comment]
Hi~ 
This bug and its corresponding solution are reported in https://github.com/pytorch/pytorch/issues/55740.
